<script setup lang="ts">
import pageTitle from "@/components/parts/pageTitle.vue"
import member from "@/components/Member/member.vue";
</script>

<template>
  <pageTitle main="Students" sub="学生" />
  
  <member
    url="@/assets/Member/murakami.png"
    name="村上総一郎/M2"
    keywards="マルチモーダルNDP・街路空間再配分・都市デザイン"
    from="埼玉県"
    hobby="ポケモン・ヒップホップ・麻雀"
  />
  <member
    url="@/assets/Member/murakami.png"
    name="玉木悠太/M2"
    keywards="マルチモーダルNDP・街路空間再配分・都市デザイン"
    from="神奈川県"
    hobby="野球・車・バンド"
  />
  <member
    url="@/assets/Member/murakami.png"
    name="田山航平/M2"
    keywards="土地利用・鉄道駅・都市集積・因果推論"
    from="神奈川県"
    hobby="カメラ・ドライブ・Jリーグ"
  />
  <member
    url="@/assets/Member/murakami.png"
    name="杉山航太郎/M2"
    keywards="人のいる空間・ファジィ理論・公共空間設計"
    from="静岡県"
    hobby="静岡県"
  />
  <member
    url="@/assets/Member/murakami.png"
    name="松村健太/M2"
    keywards="MaaS・最適化・経路推薦"
    from="山口県"
    hobby="研究室のHPを見ること・高校野球・落語鑑賞"
  />
  <member
    url="@/assets/Member/murakami.png"
    name="砂田遼大/M2"
    keywards="物流・歩行者空間"
    from="広島県"
    hobby="野球・カフェ巡り・筋トレ"
  />
  <member
    url="@/assets/Member/murakami.png"
    name="岡崎凌太/M1"
    keywards="物流最適化・配送計画・需要マネジメント"
    from="愛知県"
    hobby="研究"
  />
  <member
    url="@/assets/Member/murakami.png"
    name="櫻井由伸/M1"
    keywards="災害・リスク認知・避難所選択"
    from="宮城県"
    hobby="ディズニー・旅行・スポーツ観戦"
  />
  <member
    url="@/assets/Member/murakami.png"
    name="多田和生/M1"
    keywards="マルチモーダルNDP・駐車場配置・LRT"
    from="栃木県"
    hobby="水泳・サッカー観戦・ビアバー巡り"
  />
  <member
    url="@/assets/Member/murakami.png"
    name="鉄崎詩乃/M1"
    keywards="街路景観・景観認知・街路空間設計"
    from="東京都"
    hobby="散歩・美術館巡り・旅行"
  />
  <member
    url="@/assets/Member/murakami.png"
    name="今村啓太/B4"
    keywards="経路選択行動・街路"
    from="東京都"
    hobby="水泳・野球・LEGO"
  />
  <member
    url="@/assets/Member/murakami.png"
    name="吉村将/B4"
    keywards="都市開発・インサイト分析・地域活性化"
    from="和歌山県"
    hobby="食事・盛り上げ・食事"
  />
  <member
    url="@/assets/Member/murakami.png"
    name="和田聡/B4"
    keywards="行動モデル"
    from="東京都"
    hobby="ゲーム・将棋・テニス"
  />
</template>